### PR TITLE
Support GHC 9.0 and 9.2 #19

### PR DESCRIPTION
**Pull request by uhbif19**
Tested on 8.10, 9.0 and 9.2

### CODE REVIEW

**Comment by uhbif19** [comment]
@astynax Should I resolve conflicts on this and other PRs?

**Comment by astynax** [comment]
@uhbif19 it will be cool!

**Comment by astynax** [comment]
@uhbif19 I merged it. But I still really want to have brick's version pinned somehow: these guys quite often break stuff.

**Comment by uhbif19** [comment]
@astynax I think you should do it yourself, cuz I am does not know much about `brick` at all and found it in this project at first time.

**Pull request merged**
